# Generated by Django 4.2.15 on 2024-08-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_spam_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_spam',
            field=models.CharField(default='Not spam', max_length=20),
        ),
    ]
