# Generated by Django 4.2.15 on 2024-08-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_is_spam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_spam',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='spam_count',
        ),
    ]
